#!/bin/bash

if [[ ! -n "$PHPBREW_SKIP_INIT" ]]; then
    if [[ -f "$PHPBREW_HOME/init" ]]; then
        . "$PHPBREW_HOME/init"
    fi
fi

[[ -z "$PHPBREW_ROOT" ]] && export PHPBREW_ROOT="$HOME/.phpbrew"
[[ -z "$PHPBREW_HOME" ]] && export PHPBREW_HOME="$HOME/.phpbrew"

function phpbrew () {
    BIN='scripts/phpbrew.php'

    local exit_status
    local short_option
    export SHELL
    if [[ `echo $1 | awk 'BEGIN{FS=""}{print $1}'` = '-' ]]
    then
        short_option=$1
        shift
    else
        short_option=""
    fi
    case $1 in
        (use) if [[ -z "$2" ]]
            then
                if [[ -z "$PHPBREW_PHP" ]]
                then
                    echo "Currently using system perl"
                else
                    echo "Currently using $PHPBREW_PHP"
                fi
            else
                # checking php version exists?
                NEW_PHPBREW_PHP_PATH="$PHPBREW_ROOT/php/$2"
                if [ -d $NEW_PHPBREW_PHP_PATH ]; then
                    code=$(command $BIN env $2)
                    if [ -z "$code" ]
                    then
                        exit_status=1
                    else
                        eval $code
                        __phpbrew_set_path
                    fi
                else
                    echo "php version: $2 not exists."
                fi
            fi ;;
        (switch)
            if [[ -z "$2" ]]
            then
                command $BIN switch
            else
                $BIN use $2
                __phpbrew_reinit $2
            fi ;;
        (off)
            unset PHPBREW_PHP
            eval `$BIN env`
            __phpbrew_set_path
            echo "phpbrew is turned off." ;;
        (switch-off)
            unset PHPBREW_PHP
            __phpbrew_reinit
            echo "phpbrew is switched off." ;;
        (remove)
            if [[ -z "$2" ]]
            then
                command $BIN help
            else
              __phpbrew_remove_purge $2
            fi
            ;;
        (purge)
            if [[ -z "$2" ]]
            then
                command $BIN help
            else
              __phpbrew_remove_purge $2 purge
            fi
            ;;
        (*) command $BIN $short_option "$@"
            exit_status=$?  ;;
    esac
    hash -r
    return ${exit_status:-0}
}

function __phpbrew_set_path () {
    [[ -n $(alias perl 2>/dev/null) ]] && unalias perl 2> /dev/null

    if [[ -n $PHPBREW_ROOT ]] ; then
        export PATH_WITHOUT_PHPBREW=$(perl -e 'print join ":", grep { index($_,$ENV{PHPBREW_ROOT}) } split/:/,$ENV{PATH};')
    fi

    if [[ -z "$PHPBREW_PATH" ]]
    then
        export PHPBREW_PATH="$PHPBREW_ROOT/bin"
    fi
    export PATH=$PHPBREW_PATH:$PATH_WITHOUT_PHPBREW
    # echo "PATH => $PATH"
}

function __phpbrew_reinit () {
    if [[ ! -d "$PHPBREW_HOME" ]]
    then
        mkdir -p -p "$PHPBREW_HOME"
    fi
    echo '# DO NOT EDIT THIS FILE' >| "$PHPBREW_HOME/init"
    command $BIN env $1 >> "$PHPBREW_HOME/init"
    . "$PHPBREW_HOME/init"
    __phpbrew_set_path
}

function __phpbrew_remove_purge() {

    if [[ "$1" = "$PHPBREW_PHP" ]]
    then
        echo "php version: $1 is already in used."
        return 1
    fi

    _PHP_BIN_PATH=$PHPBREW_HOME/php/$1
    _PHP_SOURCE_FILE=$PHPBREW_HOME/build/$1.tar.bz2
    _PHP_BUILD_PATH=$PHPBREW_HOME/build/$1

    if [ -d $_PHP_BIN_PATH ]; then

        if [[ "$2" = "purge" ]]
        then
            rm -f $_PHP_SOURCE_FILE
            rm -fr $_PHP_BUILD_PATH
            rm -fr $_PHP_BIN_PATH

            echo "php version: $1 is removed and purged."
        else
            rm -f $_PHP_SOURCE_FILE
            rm -fr $_PHP_BUILD_PATH

            for FILE1 in $_PHP_BIN_PATH/*
            do
                if [[ "$FILE1" != "$_PHP_BIN_PATH/etc" ]] && [[ "$FILE1" != "$_PHP_BIN_PATH/var" ]]
                then
                    rm -fr $FILE1;
                fi
            done

            echo "php version: $1 is removed."
        fi

    else
        echo "php version: $1 not installed."
    fi

    return 0

}

