#!/usr/bin/env bash

source ${_PHPBREW_ROOT}/src/utils/echo.sh

if test -z "$1"; then
  echo_info 'Usage: '
  echo_info 'phpbrew <command> <arguments> [options]\n'
  echo_info '   help:       show this help\n'

  commands=( "${libexec_path}/*" )

  for command in ${commands}; do
    if [[ "${command}" != *phpbrew ]] && [[ "${command}" != *phpbrew-help ]]; then
      source ${command}
      command_description
    fi
  done

  exit 0
else
  command_path="$(command -v "phpbrew-$1" || true)"

  if [ ! -x "$command_path" ]; then
    source ${_PHPBREW_ROOT}/src/utils/echo.sh
    echo_fail "phpbrew: no such command \`$1'\n" >&2
    exit 1
  fi

  shift
  source "$command_path"
  command_help

  exit 0
fi
