#!/usr/bin/env bash
set -e

source ${_PHPBREW_ROOT}/src/utils/echo.sh
source ${_PHPBREW_ROOT}/src/php/versions.sh
source ${_PHPBREW_ROOT}/src/php/downloader.sh
source ${_PHPBREW_ROOT}/src/php/compiler.sh

if test -z "$1"; then
  phpbrew help install
fi

if test "$1" = 'latest'; then
  version=$(get_most_recent_version)
fi

build_dir=${_PHPBREW_ROOT}/build
install_dir=${_PHPBREW_ROOT}/php/php-${version}
sources_archive_path=${build_dir}/php-${version}.tar.bz2

if test ! -d ${build_dir}; then
  mkdir -p ${build_dir}
fi

if test ! -d ${install_dir}; then
  mkdir -p ${install_dir}
fi

cd ${build_dir} >/dev/null

echo_info "Download PHP sources for version ${version}\n"
download $version ${sources_archive_path}
