#!/bin/bash
VERSION=$(grep '^version' package.ini | sed -e 's/version *= *//')
NEWVERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g' )
perl -i -pe "s/$VERSION/$NEWVERSION/g" package.ini composer.json src/PhpBrew/Console.php
git commit -a -m "Bump version to $NEWVERSION"
