#!/bin/bash
php bin/phpbrew archive --executable \
    --exclude Tests \
    --exclude CHANGELOG\|README \
    --exclude phpunit.xml \
    --no-compress \
    --add shell \
    --bootstrap scripts/phpbrew-emb.php \
    phpbrew.phar
chmod +x phpbrew.phar
cp -v phpbrew.phar build/phpbrew
cp -v phpbrew.phar phpbrew
