#!/bin/bash
onion compile \
    --lib src \
    --lib vendor/corneltek/cliframework/src \
    --lib vendor/corneltek/pearx/src \
    --lib vendor/corneltek/getoptionkit/src \
    --lib vendor/corneltek/universal/src \
    --lib vendor/symfony/process \
    --lib vendor/symfony/yaml \
    --classloader \
    --bootstrap scripts/phpbrew-emb.php \
    --executable \
    --output phpbrew.phar
mv phpbrew.phar phpbrew
chmod +x phpbrew