#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

$command = new \cbednarski\Pharcc\Command\Build();
$command->run(new \Symfony\Component\Console\Input\ArgvInput(), new \Symfony\Component\Console\Output\NullOutput());

$phar = new Phar('phpbrew.phar');
$phar->compressFiles(Phar::GZ);
exec('mv phpbrew.phar phpbrew && chmod +x phpbrew');