#!/bin/bash
scripts/bump-version
scripts/update-init-script
bash scripts/compile
onion build

VERSION=$(grep '^version' package.ini | sed -e 's/version *= *//')
git commit -am "Releasing $VERSION"

# get version
if [[ $1 == "--tag" ]] ; then
    echo "Tagging..."
    git tag -f $VERSION -m "Releasing $VERSION"
    git remote | while read remote ; do
        git push $remote master --tags
    done
fi
