#!/bin/bash
fixture_dir=tests/fixtures/ext
for extdir in /Users/c9s/.phpbrew/build/php-5.5.17/ext/* ; do 
    extname=$(basename $extdir)
    echo $extname
    mkdir -p $fixture_dir/$extname
    cp -v $extdir/config*.m4 $fixture_dir/$extname/
    if [[ -e $extdir/package.xml ]] ; then
        cp -v $extdir/package.xml $fixture_dir/$extname/
    fi
done
